# Generated by Django 5.0.6 on 2024-08-15 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fishtype_remove_rental_posted_by_delete_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.TextField()),
                ('price', models.TextField()),
                ('date_weighin', models.DateTimeField(auto_now_add=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fishtype')),
            ],
        ),
    ]
