# Generated by Django 5.0.6 on 2024-08-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_weighin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weighin',
            old_name='price',
            new_name='price_per_kilo',
        ),
        migrations.AddField(
            model_name='weighin',
            name='total_price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
