# Generated by Django 5.0.6 on 2024-11-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_description_fishingpermit_vessel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingpermit',
            name='or_num',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
