# Generated by Django 5.0.6 on 2024-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fishingpermit_or_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingpermit',
            name='amount',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fishingpermit',
            name='date_issued',
           field=models.DateField(default='2023-07-15', blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishingpermit',
            name='fishing_gear_used',
            field=models.TextField(blank=True),
        ),
    ]
