# Generated by Django 5.0.6 on 2024-11-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_owner_name_vesselregistration_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingPermitIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField()),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_permit_incomes', to='api.fishingpermit')),
            ],
        ),
        migrations.CreateModel(
            name='VesselPermitIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField()),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_permit_incomes', to='api.fishingpermit')),
            ],
        ),
    ]
