# Generated by Django 5.0.6 on 2024-11-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_fishingpermitincome_vesselpermitincome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselpermitincome',
            name='permit',
        ),
        migrations.DeleteModel(
            name='FishingPermitIncome',
        ),
        migrations.DeleteModel(
            name='VesselPermitIncome',
        ),
    ]
