# Generated by Django 5.0.6 on 2024-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_vesselpermitincome_permit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingpermit',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
