# Generated by Django 5.0.6 on 2024-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fishingpermit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselregistration',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
