# Generated by Django 5.0.6 on 2024-11-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_vesselregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselregistration',
            name='amount',
            field=models.TextField(default='900'),
        ),
    ]
