# Generated by Django 5.0.6 on 2024-11-22 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_vesselregistration_home_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpirationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(blank=True)),
                ('date_expired', models.DateField(blank=True)),
                ('vessel_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselregistration')),
            ],
        ),
    ]
